FROM python:3.10

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update && apt-get install -y netcat-openbsd gettext httpie && rm -rf /var/lib/apt/lists/*

RUN mkdir /code
WORKDIR /code
COPY ./server.py /code/

RUN pip install --upgrade pip && \
    pip install flask

ENTRYPOINT ["python", "./server.py"]
